apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

permissions:
  scm-token-own: read
  id-token: write

jobs:
  deploy:
    steps:
      - name: get OIDC token
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          set -x +e
          curl -n -X POST -H "Authorization: ${{ cloudbees.api.token }}" -H "Content-Type: application/json" -H "Accept: application/json" -d '{}' ${{ cloudbees.api.url }}/token-exchange/oidc-id-token/audience/sts.amazonaws.com -v
      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          # aws-access-key-id: ${{ vars.aws_access_key_id }}
          # aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: arn:aws:iam::189768267137:role/cloudbees-infra-mgmt
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max.
      - name: Print CLI versions
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          echo "hello5"
          set -x +e
          aws sts get-caller-identity
          aws s3 ls
          


      # - uses: cloudbees-io/configure-eks-credentials@v0
      #   with:
      #     name: arch-saas

      # - uses: cloudbees-io/configure-ecr-credentials@v0

      # - uses: docker://alpine/helm:latest
      #   run: |
      #     helm upgrade \
      #       --namespace simple-api \
      #       --create-namespace \
      #       --install \
      #       --version ${{ needs.build.outputs.chart-version }} \
      #       app-chart ${{ needs.build.outputs.chart-location }}
